### ISSUE TITLE
能加入功能，获取指定path 下面的文件夹里面的 .log 文件吗？

### ISSUE THREAD

**Issue by david20288** [kxg3030/hyperf-log-viewer#1]
![1612258730(1)](https://user-images.githubusercontent.com/29391910/106581188-8e70b300-657d-11eb-8d76-ecad4958661e.jpg)
我这里logs 是两级目录了。 @kxg3030 @kxg2020

**Comment by kxg3030** [comment]
当然可以啦，但是好久没写php了，忘了怎么给hyperf写扩展包了。

**Comment by kxg3030** [comment]
第一版就支持指定目录的日志了，这个功能已经存在，关闭。
